root: true
env:
  browser: true
  node: true
  es6: true

parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  ecmaFeatures:
    jsx: true
    modules: true
    impliedStrict: true
    classes: true

rules:
  strict: [0]
  indent: [2, 2]
  quotes: [2, "single"]
  jsx-quotes: [2, "prefer-double"]
  comma-spacing: [0]
  consistent-return: [0]
  curly: [2, "multi-line"]
  key-spacing: [2, {beforeColon: false, afterColon: true}]
  new-cap: [0]
  no-shadow: [0]
  no-underscore-dangle: [0]
  no-use-before-define: [0]
  no-unused-vars: [0] # Necessary because of JSX
  semi: [2, "always"]
