// // Copyright (c) 2015-present, salesforce.com, inc. All rights reserved
// // Licensed under BSD 3-Clause - see LICENSE.txt or git.io/sfdc-license
//
// import React from 'react';
// import ButtonIcon from '../';
//
// export default (
//   <div>
//     {/* No Theme */}
//     <ButtonIcon />
//     <ButtonIcon
//       size="medium"
//       symbol="search"
//       aria-live="assertive"
//       aria-pressed="true"
//       tabIndex="-1"
//     />
//     <ButtonIcon
//       symbol="search"
//       disabled
//     />
//     <ButtonIcon
//       size="medium"
//       symbol="search"
//       disabled
//     />
//     <ButtonIcon
//       size="small"
//       symbol="search"
//     />
//     <ButtonIcon
//       size="x-small"
//       symbol="search"
//     />
//     <ButtonIcon
//       size="xx-small"
//       symbol="search"
//     />
//     {/* Nuetral Theme */}
//     <ButtonIcon
//       symbol="search"
//       theme="neutral"
//     />
//     <ButtonIcon
//       size="medium"
//       symbol="search"
//       theme="neutral"
//     />
//     <ButtonIcon
//       symbol="search"
//       theme="neutral"
//       disabled
//     />
//     <ButtonIcon
//       size="medium"
//       symbol="search"
//       theme="neutral"
//       disabled
//     />
//     <ButtonIcon
//       size="small"
//       symbol="search"
//       theme="neutral"
//     />
//     <ButtonIcon
//       size="x-small"
//       symbol="search"
//       theme="neutral"
//     />
//     <ButtonIcon
//       size="xx-small"
//       symbol="search"
//       theme="neutral"
//     />
//     {/* Transparent Theme */}
//     <ButtonIcon
//       symbol="search"
//       theme="transparent"
//     />
//     <ButtonIcon
//       size="medium"
//       symbol="search"
//       theme="transparent"
//     />
//     <ButtonIcon
//       symbol="search"
//       theme="transparent"
//       disabled
//     />
//     <ButtonIcon
//       size="medium"
//       symbol="search"
//       theme="transparent"
//       disabled
//     />
//     <ButtonIcon
//       size="small"
//       symbol="search"
//       theme="transparent"
//     />
//     <ButtonIcon
//       size="x-small"
//       symbol="search"
//       theme="transparent"
//     />
//     <ButtonIcon
//       size="xx-small"
//       symbol="search"
//       theme="transparent"
//     />
//     {/* Inverse */}
//     <div style={{ display: 'inline-block', padding: '0.5rem', backgroundColor: '#16325c'}}>
//       <ButtonIcon
//         symbol="search"
//         theme="inverse"
//       />
//       <ButtonIcon
//         size="medium"
//         symbol="search"
//         theme="inverse"
//       />
//       <ButtonIcon
//         symbol="search"
//         theme="inverse"
//         disabled
//       />
//       <ButtonIcon
//         size="medium"
//         symbol="search"
//         theme="inverse"
//         disabled
//       />
//       <ButtonIcon
//         size="small"
//         symbol="search"
//         theme="inverse"
//       />
//       <ButtonIcon
//         size="x-small"
//         symbol="search"
//         theme="inverse"
//       />
//       <ButtonIcon
//         size="xx-small"
//         symbol="search"
//         theme="inverse"
//       />
//     </div>
//     {/* Brand */}
//     <ButtonIcon
//       symbol="search"
//       theme="brand"
//     />
//     <ButtonIcon
//       size="medium"
//       symbol="search"
//       theme="brand"
//     />
//     <ButtonIcon
//       symbol="search"
//       theme="brand"
//       disabled
//     />
//     <ButtonIcon
//       size="medium"
//       symbol="search"
//       theme="brand"
//       disabled
//     />
//     <ButtonIcon
//       size="small"
//       symbol="search"
//       theme="brand"
//     />
//     <ButtonIcon
//       size="x-small"
//       symbol="search"
//       theme="brand"
//     />
//     <ButtonIcon
//       size="xx-small"
//       symbol="search"
//       theme="brand"
//     />
//     {/* Error */}
//     <ButtonIcon
//       symbol="error"
//       feedback="error"
//     />
//     <ButtonIcon
//       size="medium"
//       symbol="error"
//       feedback="error"
//     />
//     <ButtonIcon
//       size="small"
//       symbol="error"
//       feedback="error"
//     />
//     <ButtonIcon
//       size="x-small"
//       symbol="error"
//       feedback="error"
//     />
//     <ButtonIcon
//       size="xx-small"
//       symbol="error"
//       feedback="error"
//     />
//     <hr />
//     {/* Dropdown */}
//     <ButtonIcon
//       symbol="settings"
//       hasDropdown
//     />
//     <ButtonIcon
//       size="medium"
//       symbol="settings"
//       hasDropdown
//     />
//     <ButtonIcon
//       symbol="settings"
//       disabled
//       hasDropdown
//     />
//     <ButtonIcon
//       size="medium"
//       symbol="settings"
//       disabled
//       hasDropdown
//     />
//   </div>
// );
