name: VRT Triggered from Label

on:
  pull_request:
    types: [labeled]
  push:
    branches: ["2[0-9][02468]-*-2[0-9]"]

env:
  CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN_DSE }}

jobs:
  vrt-storybook-prepare:
    if: |
      startsWith(github.event.label.name, 'vrt:') || github.event_name == 'push'
    runs-on: salesforce-ux-emu-Ubuntu
    outputs:
      auto-accept-changes: ${{ steps.check-auto-accept-status.outputs.result }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "npm"

      - run: mkdir -p workspace

      - name: Install and Build task
        run: |
          npm ci
          npm run build

      - name: Build static Storybook
        run: npm run storybook:build
        env:
          NODE_OPTIONS: --openssl-legacy-provider # per https://candid.technology/error-error-0308010c-digital-envelope-routines-unsupported/

      - name: Archive static Storybook
        run: tar -czvf workspace/storybook.tar.gz .www/

      - name: Display structure of files
        run: ls -R
        working-directory: workspace

      - uses: actions/upload-artifact@v4
        with:
          name: storybook-build-for-chromatic
          path: workspace/storybook.tar.gz

      - name: Check if chromatic baselines should be auto-accepted
        id: check-auto-accept-status
        uses: ./.github/actions/baseline-auto-accept-checks
        with:
          auto-accept-branches: ${{ vars.AUTO_BASELINE_ACCEPT_BRANCHES }}

  vrt-chromatic:
    # if: ${{ (1 < 0) }}
    runs-on: salesforce-ux-emu-Ubuntu
    needs:
      - vrt-storybook-prepare
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # retrieve git history

      - uses: actions/setup-node@v3
        with:
          cache: "npm"

      - uses: actions/download-artifact@v4
        with:
          name: storybook-build-for-chromatic
          path: workspace

      - name: Display structure of downloaded files
        working-directory: workspace
        run: ls -R

      - name: Decompress storybook
        working-directory: workspace
        run: tar -xvf storybook.tar.gz

      - name: Publish dse-system-internal to chromatic #turbo snapshots disabled
        id: chromatic
        uses: chromaui/action@v10
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_DSE }}
          storybookBuildDir: workspace/.www
          exitZeroOnChanges: true
          exitOnceUploaded: true
          autoAcceptChanges: ${{ needs.vrt-storybook-prepare.outputs.auto-accept-changes }}

      - name: Find Chromatic Comment
        uses: salesforce-ux-emu/find-comment@v1.0.0
        id: find-chromatic-comment
        if: needs.vrt-storybook-prepare.outputs.auto-accept-changes == 'false'
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Chromatic Results for

      - name: Publish Chromatic results to GitHub
        uses: salesforce-ux-emu/create-or-update-comment@v1.0.0
        id: post-chromatic-comment
        if: needs.vrt-storybook-prepare.outputs.auto-accept-changes == 'false'
        with:
          comment-id: ${{ steps.find-chromatic-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Chromatic Results for PR #${{ github.event.pull_request.number }} :rocket:
            - Build URL :  ${{ steps.chromatic.outputs.buildUrl }}
            - Storybook Preview : ${{ steps.chromatic.outputs.storybookUrl }}
            - Component Count : ${{ steps.chromatic.outputs.componentCount }}
          edit-mode: replace
